FROM node:latest as builder

WORKDIR /app
COPY package.json ./
RUN yarn install
COPY . .
RUN yarn run build

FROM nginx:latest
#COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
